Merge bash scripts to main branch
wolender/Ugrid pull request #1
Opened 2023-06-26 11:51 UTC by wolender

I added all of the tasks from "Scripting Bash" module.

2023-06-26 13:09 UTC, vasichkin commented
Please, organise code in folders - task1, task2, etc.

2023-06-26 13:30 UTC, wolender commented
I fixed project structure

2023-06-26 16:19 UTC, vasichkin requested changes
Some tasks failed

2023-06-26 16:19 UTC, vasichkin commented on caesar/caesar.sh
> +#use example
Please, add task definition

2023-06-26 16:19 UTC, vasichkin commented on bash/task1/fibonacci.sh
Approved

2023-06-26 16:19 UTC, vasichkin commented on bash/task2/oppars.sh
C11233:task2 vkhomenko$ ./oppars.sh -o * -n 1 -1 -d
User: vkhomenko
Script: ./oppars.sh
Operation: oppars.sh
Numbers: 2
The ressult is : 1

2023-06-26 16:19 UTC, vasichkin commented on bash/task3/fizzbuzz.sh
Approved

2023-06-26 16:19 UTC, vasichkin commented on bash/task4/caesar.sh
C11233:task4 vkhomenko$ cat input.txt
hello world
C11233:task4 vkhomenko$ ./caesar.sh -s 10 -i input.txt -o cipher.txt
C11233:task4 vkhomenko$ cat cipher.txt
rovvy gybvn
C11233:task4 vkhomenko$ ./caesar.sh -s -10 -i cipher.txt -o restored.txt
C11233:task4 vkhomenko$ cat restored.txt
hello ]oXld

2023-06-26 16:19 UTC, vasichkin commented on bash/task5/task5.sh
C11233:task5 vkhomenko$ ./task5.sh -i input.txt -o result.txt -s XX dd
No outputfile
C11233:task5 vkhomenko$ ./task5.sh -i input.txt -o output.txt -r
./task5.sh: line 37: tac: command not found

2023-06-26 16:19 UTC, vasichkin commented on bash/task6/task6.sh
Approved

2023-06-27 11:09 UTC, wolender commented
fixed all the issues

2023-06-27 14:10 UTC, vasichkin requested changes

2023-06-27 14:10 UTC, vasichkin commented on bash/task2/oppars.sh
Approved

2023-06-27 14:10 UTC, vasichkin commented on bash/task4/caesar.sh
Approved

2023-06-27 14:10 UTC, vasichkin commented on bash/task5/task5.sh
C11233:task5 vkhomenko$ cat input.txt
Hello student
HOW are you?
XX to replace by YY
!@#$^&
the END
C11233:task5 vkhomenko$ ./task5.sh -i input.txt -o result.txt -l
C11233:task5 vkhomenko$ cat result.txt

C11233:task5 vkhomenko$

2023-06-27 14:23 UTC, vasichkin approved these changes

2023-06-27 14:23 UTC, vasichkin commented on bash/task5/task5.sh
Approved

2023-06-27 14:26 UTC, merged